redeloyment

diff --git a/week8/Jenkinsfile b/week8/Jenkinsfile
--- a/week8/Jenkinsfile
+++ b/week8/Jenkinsfile
@@ -11,7 +11,7 @@ spec:
     - 99d
     volumeMounts:
     - name: shared-storage
-      mountPath: /mnt        
+      mountPath: /mnt
   - name: kaniko
     image: gcr.io/kaniko-project/executor:debug
     command:
@@ -37,21 +37,24 @@ spec:
 ''') {
   node(POD_LABEL) {
     stage('Checkout') {
-      checkout scm: [$class: 'GitSCM', userRemoteConfigs: [[url: 'https://github.com/MoiseGermain/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git']], branches: [[name: "*/${BRANCH_NAME}"]]]
-      sh 'git branch'
-      sh 'git checkout ${BRANCH_NAME}'
+      // Explicitly specify branch for checkout
+      checkout scm: [userRemoteConfigs: [[url: 'https://github.com/MoiseGermain/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git']], branches: [[name: "*/${BRANCH_NAME}"]]]
+      sh 'pwd'
       sh 'ls -lah'
+      // Ensure we're in the correct directory
     }
 
     stage('Prepare Environment') {
       container('gradle') {
+        // Confirm the directory structure
         sh 'pwd'
         sh 'ls -la'
+        // Attempt to change directory
         sh '''
         cd Chapter08/sample1
         chmod +x gradlew
         '''
-        // Conditional logic based on branch
+        // Conditional logic for modifying build.gradle based on the branch
         if (env.BRANCH_NAME == 'main') {
           sh '''
           sed -i 's/minimum = 0.2/minimum = 0.1/' build.gradle
@@ -69,15 +72,15 @@ spec:
     stage('Build') {
       container('gradle') {
         sh './gradlew build'
-        sh 'mv ./build/libs/calculator-0.0.1-SNAPSHOT.jar /mnt'
+        // Move the JAR file to a shared volume if present
+        sh 'mv ./build/libs/calculator-0.0.1-SNAPSHOT.jar /mnt || echo "Build artifact not found!"'
       }
     }
 
     stage('Build and Push Docker Image') {
-      // Conditional logic to build image only if branch is not 'playground'
       if (env.BRANCH_NAME != 'playground') {
         container('kaniko') {
-          // Set image name based on branch
+          // Determine image name and version based on branch
           imageName = (env.BRANCH_NAME == 'release') ? 'calculator' : 'calculator-' + env.BRANCH_NAME
           imageVersion = (env.BRANCH_NAME == 'release') ? '1.0' : '0.1'
 
@@ -85,6 +88,7 @@ spec:
           echo 'FROM openjdk:8-jre' > Dockerfile
           echo 'COPY ./calculator-0.0.1-SNAPSHOT.jar app.jar' >> Dockerfile
           echo 'ENTRYPOINT ["java", "-jar", "app.jar"]' >> Dockerfile
+          // Ensure the artifact is moved before attempting to build the image
           mv /mnt/calculator-0.0.1-SNAPSHOT.jar .
           /kaniko/executor --context `pwd` --destination mogermain/${imageName}:${imageVersion}
           '''
